### PR TITLE
fix problem which will make the signature bitmap be black.

### PR DESCRIPTION
**Pull request by PPTing**
when create bitmap with

```
Bitmap.createBitmap(this.getWidth(),this.getHeight(),Bitmap.Config.RGB_565);
```

It will make the png file background  be black.

### CODE REVIEW

**Comment by cany-dev** [comment]
Thanks for the issue! I can't reproduce your question([Example](https://github.com/zoomyu/react-native-signature-view/blob/master/example)).Can you provide a example to reproduce this issue?

**Comment by PPTing** [comment]
@zoomyu Hi 
I use SignatureView in React Native code like below 

```
<SignatureView
    ref={(c) => {
        this.signatureView = c
    }}
    style={styles.signatureViewStyle}
    watermarkString={""}
    watermarkSize={14}
    watermarkColor={'#00000000'}
    signatureColor={'#000000'}
    watermarkLineSpacing={20}
    watermarkWordSpacing={10}
    watermarkAngle={360}
    onSaveEvent={(msg) => {
        console.log('onSaveEvent --->>', msg);
    }}
/>
```

When I call `this.signatureView._saveSignature();` function , I get a png file like below.
Maybe the different form your code is that I set the props `watermarkString` to `""`.

screen shot 2018-02-08 at 15 10 59

So I review your Java code and I found that you create a Bitmap with 

```
Bitmap signatureBitmap = Bitmap.createBitmap(this.getWidth(), this.getHeight(),
                Bitmap.Config.RGB_565);
```
It will make the png file background color looked be black.

So I change it to ARGB_8888.

**Comment by cany-dev** [comment]
@PPTing 
I still can't reproduce this question.Example:

```
import React, { Component } from 'react';
import { StyleSheet, TouchableOpacity, Text, View } from 'react-native';

import SignatureView from 'react-native-signature-view';

export default class Root extends Component {

  render() {
    return (
      <View style={styles.container}>
        <SignatureView
          ref={(c) => {
            this.signatureView = c;
          }}
          style={styles.signatureViewStyle}
          watermarkString={''}
          watermarkSize={14}
          watermarkColor={'#00000000'}
          signatureColor={'#000000'}
          watermarkLineSpacing={20}
          watermarkWordSpacing={10}
          watermarkAngle={360}
          onSaveEvent={(msg) => {
            console.log('onSaveEvent --->>', msg);
          }}
        />

        <View style={styles.buttonTab}>
          <TouchableOpacity
            style={styles.button}
            onPress={this._resetSign.bind(this)}
          >
            <Text>Redrawed</Text>
          </TouchableOpacity>
          <TouchableOpacity
            style={styles.button}
            onPress={this._saveSign.bind(this)}
          >
            <Text>Save</Text>
          </TouchableOpacity>
        </View>
      </View>
    );
  }

  _resetSign = () => {
    this.signatureView._resetSignature();
  }

  _saveSign = () => {
    this.signatureView._saveSignature();
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5FCFF'
  },
  signatureViewStyle: {
    flex: 1
  },
  signatureView: {
    flex: 1
  },
  buttonTab: {
    height: 48,
    flexDirection: 'row'
  },
  button: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center'
  }
});
```
  

### My Environment

| software         | version
| ---------------- | -------
| react-native-cli | 2.0.1
| react-native     | 0.50.3
| node             | v8.9.1
|  yarn      | 1.3.2
| device		   | samsung s5

>React Native not supporting `'#00000000'` (`watermarkColor={'#00000000'}`).

**Comment by PPTing** [comment]
@zoomyu I'm sorry 
I forgot that I also changed the Java code in `RCTSigntureView` class like below

```
setBackgroundColor(Color.WHITE); -> setBackgroundColor(Color.TRANSPARENT);
```

I need the RCTSigntureView view to be transparent so it can show the other view behind it,like an ImageView or others. So I change the background color to transparent. So when I call the function `getSignature()` I got an png file with black background because the bitmap was created by 
`Bitmap.createBitmap(this.getWidth(), this.getHeight(),Bitmap.Config.RGB_565);`

So sorry for that. Please close this PR.

**Pull request closed without merging**
